package dev.lucas.portfolio.feature.tripplanner.theme

import androidx.compose.ui.graphics.Color

// Light — Horizon
val LightPrimary             = Color(0xFF4A50A3)
val LightOnPrimary           = Color(0xFFFFFFFF)
val LightPrimaryContainer    = Color(0xFFDDE1FF)
val LightOnPrimaryContainer  = Color(0xFF00006C)
val LightSecondary           = Color(0xFF5D5B72)
val LightOnSecondary         = Color(0xFFFFFFFF)
val LightSecondaryContainer  = Color(0xFFE2DFFF)
val LightOnSecondaryContainer= Color(0xFF1A1855)
val LightTertiary            = Color(0xFF7A4E7E)
val LightOnTertiary          = Color(0xFFFFFFFF)
val LightTertiaryContainer   = Color(0xFFF7D8FF)
val LightOnTertiaryContainer = Color(0xFF300045)
val LightBackground          = Color(0xFFF5F0FF)
val LightOnBackground        = Color(0xFF1C1B1F)
val LightSurface             = Color(0xFFFFFBFF)
val LightOnSurface           = Color(0xFF1C1B1F)
val LightSurfaceVariant      = Color(0xFFE7E0EC)
val LightOnSurfaceVariant    = Color(0xFF49454E)
val LightOutline             = Color(0xFF7A757F)
val LightOutlineVariant      = Color(0xFFCAC4CF)
val LightError               = Color(0xFFBA1A1A)
val LightOnError             = Color(0xFFFFFFFF)
val LightErrorContainer      = Color(0xFFFFDAD6)
val LightOnErrorContainer    = Color(0xFF410002)
val LightInverseSurface      = Color(0xFF313033)
val LightInverseOnSurface    = Color(0xFFF4EFF4)
val LightInversePrimary      = Color(0xFFBEC2FF)

// Dark
val DarkPrimary              = Color(0xFFBEC2FF)
val DarkOnPrimary            = Color(0xFF141872)
val DarkPrimaryContainer     = Color(0xFF31378A)
val DarkOnPrimaryContainer   = Color(0xFFDDE1FF)
val DarkSecondary            = Color(0xFFC6C3E3)
val DarkOnSecondary          = Color(0xFF2F2D42)
val DarkSecondaryContainer   = Color(0xFF454359)
val DarkOnSecondaryContainer = Color(0xFFE2DFFF)
val DarkTertiary             = Color(0xFFE6B4EB)
val DarkOnTertiary           = Color(0xFF48194E)
val DarkTertiaryContainer    = Color(0xFF613666)
val DarkOnTertiaryContainer  = Color(0xFFF7D8FF)
val DarkBackground           = Color(0xFF141318)
val DarkOnBackground         = Color(0xFFE6E1E6)
val DarkSurface              = Color(0xFF141318)
val DarkOnSurface            = Color(0xFFE6E1E6)
val DarkSurfaceVariant       = Color(0xFF49454E)
val DarkOnSurfaceVariant     = Color(0xFFCAC4CF)
val DarkOutline              = Color(0xFF948F99)
val DarkOutlineVariant       = Color(0xFF49454E)
val DarkError                = Color(0xFFFFB4AB)
val DarkOnError              = Color(0xFF690005)
val DarkErrorContainer       = Color(0xFF93000A)
val DarkOnErrorContainer     = Color(0xFFFFDAD6)
val DarkInverseSurface       = Color(0xFFE6E1E6)
val DarkInverseOnSurface     = Color(0xFF313033)
val DarkInversePrimary       = Color(0xFF4A50A3)
